# Site settings
title: Zoom Data Fence
description: Data Warehouse Security Management Tool
url: "https://zoom.github.io"
baseurl: "/zoom-data-fence"

# Build settings
markdown: kramdown
highlighter: rouge
theme: null
remote_theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme settings
show_downloads: false

# Navigation
navigation:
  - title: Zoom Data Fence
    url: /
  - title: Why We Made Data Fence
    url: /why-we-made-data-fence
  - title: Contributing
    url: /contributing
  - title: Getting Started
    url: /getting-started
  - title: Install Docker Image
    url: /install-docker-image
  - title: Defining Roles
    url: /defining-roles
  - title: Connecting to a Database
    url: /profiles
  - title: Variables
    url: /variables
  - title: Importing Roles
    url: /importing-roles
  - title: Install Java Package
    url: /install-java-package
