name: build-docker
permissions:
  contents: read
on:
  push:
    branches:
      # Build Snapshots From Main
      - main
    tags:
      # Build Releases From Tags
      - [0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    environment: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Determine if Deploy
        id: build-meta
        uses: ./.github/workflows/check-deploy
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            zoomvideo/zoom-data-fence
          tags: |
            type=raw,value=latest,enable=${{ steps.build-meta.outputs.release }}
            type=raw,value=v${{ steps.build-meta.outputs.version }}
      - name: Login to Docker Hub
        if: ${{ steps.build-meta.outputs.deploy }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ steps.build-meta.outputs.deploy }}
          provenance: mode=max
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
        if: ${{ steps.build-meta.outputs.deploy }}
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: zoomvideo/zoom-data-fence
          short-description: ${{ github.event.repository.description }}

